#!/bin/bash
#SBATCH -J BehavClon
#SBATCH --ntasks=1
#SBATCH --partition=t4v1,p100
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH -c 2 # Number of cpus requested
#SBATCH --output ../OUTPUTS/behavCloning_ml4h-%j-%a.out
#SBATCH --export=ALL
#SBATCH --mem=8GB
#SBATCH --array=1-108%20
# SLURM_ARRAY_TASK_ID=${SLURM_ARRAY_TASK_ID:-1}
#echo $(tail -n +$SLURM_ARRAY_TASK_ID BC_exp_params.txt | head -n1)


# python -u scripts/train_behavCloning_with_command_line_args.py $(tail -n+$SLURM_ARRAY_TASK_ID slurm_scripts/BC_exp_params.txt | head -n1)
while IFS= read -r line; do
    echo "Running experiment with parameters: $line"
    python -u scripts/train_behavCloning_with_command_line_args.py $line
done < slurm_scripts/BC_exp_params.txt