device: 'cpu' # or 'cuda'
random_seed: 1234 # updated by run scripts
folder_name: 'temp_folder_name' # updated by run scripts
resume: False
minibatch_size: 128
drop_smaller_than_minibatch: True
sided_Q: 'negative'  #Can be 'positive' or 'negative'
perception_neg_traj_ratio: 'NA'

state_dim: 33                      
num_actions: 25   
context_dim: 5                     # Number of context/demographic/binary indicator variables we'll use as input
dem_context: False

# update these manually
storage_path: 'test/'

# where train, val and test tuples are
train_data_file: 'data/sepsis_mimiciii/train_set_tuples'
validation_data_file: 'data/sepsis_mimiciii/val_set_tuples'
test_data_file: 'data/sepsis_mimiciii/test_set_tuples'

behav_policy_file_wDemo: 'data/behaviour_clone/BC_l1e-5_n64_w0_sgd_withDemo/BC_model.pt' 
behav_policy_file: 'data/behaviour_clone/BC_l1e-5_n64_w0_sgd/BC_model.pt' # Pick the best behaviour cloning policy
